import json, pathlib, subprocess, hashlib, re, shutil, datetime
ROOT=pathlib.Path('/private/tmp/kd-review49-benefit-audit-20260917')
OUT=pathlib.Path(__file__).parent
BASE='14804ce389d69114feed27b92fb11ac78423cc0e'
CANDIDATE='a69a32be51d8258fc4604d925f03ff35d74b4da6'
# Independent assessments; previous report is used below only as a source/test index.
DATA='''
E01-001|Gespeicherte, noch nicht aufgelöste Titelpins bleiben auf Start sichtbar; der fehlende Katalog wird gezielt angefordert.|Ein ausstehender Zustand und höchstens ein Vollabruf je Owner/Mount kommen hinzu.|Der erste betroffene Start kann einen großen Vollkatalog laden. Offline oder bei Mehrdeutigkeit bleibt der Pin ausstehend; kein Löschrisiko und keine behauptete Auflösung.|Frischer Mount zeigt den gespeicherten ausstehenden Pin statt leer.~Verzögerte Antwort löst den Pin auf; Klick führt zu Watchmode 901.~Missing, Fehler und Mehrdeutigkeit erhalten identische Speicherbytes.~Leerbestand, Known-Treffer, Must-Watch und Kinopins vermeiden den Zusatzabruf.~Echter StartTab und Pin-Hook mit extrahierten unveränderten App-Callbacks durchlaufen Save/Unmount/Remount in beiden Browsern.
E01-002|Die nächsten fünf Kinopins bleiben am Jahreswechsel tatsächlich die nächsten fünf.|Sortiert den Rohtermin einschließlich Jahr vor Formatierung und Limit.|Sehr kleine lokale Projektion. Ungültige Termine stehen weiterhin hinten; keine neue globale Datumsschicht.|Normierte sechs Programmeinträge liefern am festen 31.12. die erwarteten ersten fünf.~Dezembertermin steht vor Januar.~Gleichjähriges Datum, Uhrzeit und Limit bleiben geprüft.~Echte Programmnormierung und Katalogauflösung laufen mit; fehlende Treffer werden nicht künstlich erzeugt.~Bestehender kinoPinTermin liest das ISO-Jahr vor der Anzeigeumwandlung.
E02-001|Verspätete Refresh-Ergebnisse stellen ausgeloggte Sitzungen nicht wieder her und beschädigen keinen späteren Login.|Logininstanz plus Credentialversion binden jeden Commit; kurze IDB-Transaktion serialisiert browserübergreifend.|Höchste zusätzliche Clientkomplexität der Serie. Bei fehlendem sicherem Browsermutex werden Credential-Commits bewusst abgelehnt. HTTP liegt außerhalb des Mutex; alte Browser ohne diesen Commitvertrag bleiben ein gemischter Clientfall.|Late Success nach Logout lässt Sessionkey gelöscht; Resume bleibt Gast.~Neuer B-Login überlebt späten A-Erfolg und invalid_grant.~Neue Sitzungs-ID trennt auch erneuten Login desselben Kontos; native Zwei-Tab-Tests laufen mit und ohne Web Locks.~Normale Rotation, terminales invalid_grant, Offlineerhalt und Single-Flight bleiben positiv/negativ geprüft.~39 Authprüfungen und 18 native Browserfälle prüfen echte Persistenz, Snapshot, Mutex/Fallback und Resume.
E02-002|Ein serverseitig abgelehnter, lokal frischer Bearer kann nach 401 tatsächlich erneuert werden.|Force trägt die Identität des abgelehnten Tokens bis zum Refresh; ein inzwischen anderer gültiger Bearer darf übernommen werden.|Teilt den Commitvertrag mit E02-001. Zusätzliche Rotation entsteht nur für den abgelehnten Bearer; keine unbeschränkte Retrystufe.|401 führt zu genau einem Refresh und einem REST-Retry mit neuem Bearer.~Web-Lock-/Fallback- und Uhrversatzfälle sind im Authgestell enthalten.~Im Lock erneuerter Token wird übernommen; Konto-/Loginwechsel wird abgebrochen.~Regulär frischer Token bleibt requestfrei; regulärer/erzwungener paralleler Lauf verliert Force nicht.~Zweites 401 und fehlende Erneuerbarkeit enden begrenzt und ohne lokale Datenlöschung.
E02-003|Ein fehlgeschlagener RLS-Prüflauf hinterlässt seine eigenen Proben nicht unnötig.|Probeabsicht wird vor dem Write registriert; gemeinsames finally bereinigt jede Probe separat und wertgebunden.|Mehr Testwerkzeugcode und gezielte Cleanup-Reads. Unklare/geänderte Daten werden erhalten; Cleanupfehler bleiben sichtbar und dürfen den ursprünglichen Fehler nicht grün machen.|T3-Abbruch nach erfolgreichem Write räumt As eigene Probe auf und endet weiter rot.~Fehlgeschlagenes Cleanup verhindert andere Bereinigungen nicht; sichere Probezuordnung bleibt im Fehler.~Fremde/geänderte Werte und vorhandene Profile werden erhalten.~Abbruch vor Erstprobe löscht nichts; Folgeausführung kann den bereinigten Topf nutzen.~Tatsächlich ausgeführtes Original-CLI mit Mockfetch deckt normalen A/B/Profil/Shared-Abschluss ab.
E03-001|Ein alter Pull kann einen inzwischen bestätigten neueren Kontowert nicht zurücksetzen.|Vergleicht Remote-Revision vor Cache, Metadaten und Veröffentlichung.|Kleine monotone Übernahmeprüfung im vorhandenen Driver. Sie ordnet Antworten, ohne alle Requests global zu serialisieren.|Deferred GET Revision 1 nach PATCH Revision 2 lässt Wert und Revision 2 bestehen.~Folgemutation baut auf dem bestätigten Wert auf.~Neuerer erlaubter Remote-Stand wird übernommen und publiziert.~Pending, Konflikt, Ablehnung und ungültiger Accountkontext bleiben geschützt.~Erfolgreicher Snapshot bleibt Voraussetzung des erlaubten Überschreibens.
E03-002|Ein leeres oder sparsames Konto erhält keine Gastreste beim Login.|Nur Kontoadoption ersetzt auch fehlende Remote-Töpfe; alltäglicher Pull bleibt erhaltend.|Eine explizite Optionsweitergabe statt globaler Löschsemantik. Zusätzliche Null-/Löschreadbacks während des Übergangs; Fehler führen weiterhin zu Restore oder Privacy-Lock.|Leeres Konto wird ohne persönliche Uploads account-ready und zeigt keine Gasttöpfe.~Sparsames Konto übernimmt vorhandene Werte und entfernt fehlende Gastreste.~Neue Kontoinhalte bauen auf dem bereinigten Konto auf.~Logout stellt den Gastrohbestand bytegleich wieder her.~Snapshot-, Pull-, Silent-replace- und Restorefehler werden im echten Übernahme-/Driververbund erprobt.~Normale Pending-Kontoänderungen bleiben erhalten; ausdrückliche Gastübernahme bleibt separat geprüft.
E03-003|Der positive Löschschutztest erreicht wieder seine eigentlichen Folgeprüfungen.|Die vollständige Gastfixture enthält gültige leere Entdecken-Pins.|Reine Testdatenkorrektur; keine Lockerung der Produktregistry. Heute zehn statt ursprünglich neun Checks durch zusätzliche Vollständigkeitsprüfung.|Einzeltest läuft vollständig; alle ursprünglichen neun plus neue Fixtureprüfung bestehen.~Leeres Pin-JSON ist registrykonform und macht Backup vollständig.~Defektes JSON sperrt Löschung weiterhin.~Kontextwechsel, stiller Teilfehler/Rollback und Kontowechsel werden nach dem positiven Fall wirklich ausgeführt.
E04-001|Blogabgleich verwechselt gleichnamige Remakes oder Werkarten weniger leicht.|Must-Watch-Projektion erhält Jahr und Typ; Masterersetzung nutzt dieselbe Referenzprojektion.|Sehr kleine Vertragserhaltung; unbekannte alte Metadaten werden nicht erfunden. Bereits bewusst gesetzte Refs bleiben stabil.|The Thing 1982 versus 2011 erzeugt keinen Auto-Link.~Dark 2017 Serie wird eindeutig verlinkt.~Normalabgleich, Rotlinkheilung und Masterersetzung führen durch dieselbe Projektion.~Jahr/Typ bleiben erhalten, Eingaben unverändert.~Mastertreffer, Mehrdeutigkeit, metadatenarmer Altbestand und gesetzte Refs sind Gegenproben.
E04-002|Bearbeitete KI-Vorschläge erhalten einen zum endgültigen Inhalt passenden Status und Herkunftstext.|FilmCard und EintragForm teilen einen reinen Inhaltsvergleich; Notizen zählen nicht als Bewertungsänderung.|Elf Zeilen gemeinsame Fachlogik ersetzen divergierende Entscheidungen. Auch manuell exakt gleiche Inhalte können nun angenommen heißen; das Urteil folgt Inhalt statt Einstiegsknopf.|Unveränderte offene Übernahme bleibt angenommen mit unverändertem Prognoseergebnis.~Achse, Kategorie und Begründung erzeugen korrigiert samt sichtbarer UI und korrekter Herkunft.~Bereits angenommene Prognose kann über denselben Weg korrigiert werden.~Notiz und Rücksetzen auf Originalwerte bleiben angenommen.~Manueller Einstieg, unvollständige Übernahme und Speicherfehler sind aktiv geprüft; Formular verwendet denselben gelesenen Vergleich.
E04-003|Ein Must-Watch-Masterlink führt trotz zuvor gesetzter Mediathekfilter zu einer sichtbaren geöffneten Karte.|Navigation stellt passende Ansicht/Typ/Filter her und quittiert erst nach sichtbarer Projektion plus DOMziel.|Mehr UIzustand im bestehenden Fokuspfad; bewusstes Zurücksetzen der Filter ist sichtbare Navigationswirkung. Kein neuer Navigationsmanager.|Alpha-Suche zu Zulu-Link öffnet sichtbare Zulu-Karte.~Fehlendes/hidden/inert Ziel verbraucht den Auftrag nicht.~Such-, Genre-, Kategorie-, Besitz-, Buchstaben- und Dekadenfälle laufen gemountet.~Ungefilterter Pfad, Typwechsel und Auswahlmodus erhalten Vertrag; null Datenwrites.
E04-004|Eine Jahreszahl lässt sich schrittweise bearbeiten, ohne bei jedem Tastendruck gelöscht zu werden.|Lokaler Stringentwurf mit ausdrücklicher Bestätigung trennt Eingabe von persistentem Jahr.|Zusätzlicher Entwurfszustand und Speichern/Abbrechen-Schritte sind angemessen; andere Metadaten bleiben unverändert. Ungültige Eingabe wird nicht als Nullwert gespeichert.|Echte Liste/Controller halten 1,19,198,1982 über Ticks; Commit schreibt numerisch 1982.~Backspace von 1982 auf 198 bleibt Entwurf; Ergänzung zu 1983 speichert korrekt.~Bewusst bestätigtes Leeren schreibt null; ungültiger nichtleerer Wert überschreibt kein Jahr.~Paste, Neuerfassung, Escape/Abbruch und Fehler lassen nur gültige Werte in Persistenz.
E04-005|Teilweise gespeicherte Stapel verlieren weder die fehlgeschlagenen Eingaben noch erzeugt Retry Dubletten.|Speicherergebnis wird je Kandidat festgehalten; nur fehlgeschlagene Kandidaten verbleiben in der Vorschau.|Mehr Ergebnis-/UIzustand, aber kein neues Batchframework. Null bleibt konservativ nicht gespeichert, auch wenn es eine Dublette statt Transportfehler war.|id/null/id erhält exakt Restkandidat samt Quelle, Staffeln, Faktenwahl und Auswahl.~Retry adressiert nur den Rest, kein zweiter KI-Lauf.~null/null/null erhält alle korrigierten Kandidaten.~Gesamterfolg schließt; laufende Speicherung verhindert doppelte Übernahme.~Kontextwechsel stoppt Rest/Abschlussanzeige; unklare Nullergebnisse bleiben konservativ erhalten.
E04-006|Der im Blog sichtbare Werktyp entspricht beim Anlegen dem gespeicherten Typ.|FilmForm leitet einen sofort gültigen effektiven Typ aus aktuellen erlaubten Optionen ab.|Kleine Synchronisation zwischen äußerer Auswahl und bestehendem Entwurf; direkter Typwechsel bewahrt sonstige Eingaben.|Beide Blogwege speichern Film zu Serie und Serie zu Film korrekt.~Innere/äußere Auswahl, Validierung und Save benutzen denselben effektiven Typ.~Unveränderter Typ und Umwege über Musik/Sonstiges sind geprüft.~Eigener Titelentwurf überlebt direkten Wechsel.~Referenz entsteht erst nach bestätigter Anlage; alle Wege mit echten Komponenten und null Netz.
E05-001|Gemischte Kataloggenerationen können entfernte Streamingangebote nicht als aktuell wiederbeleben.|Ein nicht passendes Known/Discover-Paar wird beschränkt markiert und darf keine alte Dienstunion bilden.|Bei Ausfall wird weniger Verfügbarkeit gezeigt, dafür keine falsche aktuelle Verfügbarkeit. Der Konflikt bleibt wiederherstellbar; progressive Seiten bleiben eigene Generationen.|Known A/Discover B/Cache A entfernt alten Dienst und Link aus Finder/Mein Programm.~Throw-ohne-Cache und falscher erfolgreicher Nachzug sind eigene Fälle.~Konflikt bleibt sichtbar; späterer passender Nachzug heilt ihn.~Herkunft meldet abgelaufen/generationKonflikt statt frischen Vollkatalog.~Passendes B entfernt Altangebot; gleiches B/B bewahrt legitime Union.~Alles/Neu erhalten begrenzten Umfang; unabhängige progressive Fristen-/Browserprüfungen bleiben grün.
E05-002|Serien erhalten passende bestätigte Fakten statt durch eine falsche RPC-Werkart leer auszugehen.|Normalisiert an genau der SQL-Grenze auf film/series.|Einzeiliger Adaptervertrag statt Änderung interner serie-Werte; keine Migration für dieses Ticket.|IMDb-only und TMDB-only Serien außerhalb Charts werden durch echte SQL-Validierung aufgelöst.~serie und series werden beide zu series am RPC; interner Forecast bleibt serie.~Film, direkte ID und Chartfallback funktionieren.~Fehlendes/widersprüchliches Jahr sowie IDkonflikte/Mehrdeutigkeit liefern keinen unsicheren Fakt.~PG17-Test führt echten Reader gegen echte SQL-Funktion aus; kein argumentblinder Erfolgsstub.
E05-003|Falsylegacy-IDs werden tatsächlich ersetzt; neu angelegte Sonderzeichentitel bleiben erreichbar.|Zentraler Normalisierer schreibt generierte ID nach Originalfeldern, addFilm verwendet das normalisierte Ergebnis.|Minimaler Fix an den zwei echten Identitätsgrenzen. Zufallsfallback für nicht sluggierbare Titel bleibt bestehendes Verhalten.|Null, Leerstring, fehlend und weitere Falsywerte werden eindeutig/stabil normalisiert.~Bestehende IDs und beide Kollisionsarten bleiben geprüft.~Musik mit !!! und leerem Jahr persistiert samt echter Rückgabe-ID.~Zweiter Sonderzeichentitel wird nicht pauschal als leere Dublette verworfen.~Normalisierte Altpaare bleiben beim Einzeledit getrennt; echter Appcallback und Controllerkontrolle laufen.
E06-001|Progressive Streamingseiten zeigen abgelaufene Quellen nicht mehr als aktuell.|Quellfrist wird von Neu-Frist getrennt durch RPC, Cache, Controller und UI getragen.|Etwas mehr Fristzustand; alte Items können als veraltet sichtbar bleiben. Ein HTTP200 erneuert fachliche Frische nicht. Additive Antwortfelder sind für bisherigen normalisierenden Leser verträglich.|Offener Tab und Wiederaufnahme erkennen Quellablauf unabhängig von Known.~Stale200 bleibt stale mit identischer Quellfrist.~Cache berücksichtigt endliche Frist; null erfindet keine Frist.~Schon beim Start abgelaufene Quelle wird sichtbar erkannt.~Neuer gültiger Stand hebt Warnung auf; keine Refreshschleife.~PG17/React, Cachetest und beide Browser prüfen die zusammenhängenden Ebenen.
E06-002|Gelöschte Mediathekeinträge blockieren erneutes Anlegen aus Streaming nicht mehr.|Navigation, Erstellen und Gesehenübernahme nutzen dieselbe aktuell bestätigte Zuordnung.|Keine pauschale Löschung historischer Gesehenfelder. Bei noch ungeladenem Master bleiben Aktionen vorsichtig; vorhandener gecachter Identitätsindex vermeidet wiederholten Vollindexbau.|Alles: Anlegen, löschen, erneut erstellen läuft durch echte UI/Controller.~Neu durchläuft denselben Ablauf.~Gesehenstatus bleibt erhalten, verwaiste ID blockiert Übernahme nicht.~Vorhandene eindeutige Verknüpfung navigiert und verhindert doppelte Anlage.~Unvollständiger Master, Accountwechsel und Teilseite werden nicht als Bestandslöschung interpretiert.
E06-003|Persönliche Neu-Fenster werden nach abgeschnittenen Quelldiffs nicht neu gestartet.|RPC liefert belegten Beginn und Verbrauchszeit; owner-/dienstgebundenes Fristenbuch übernimmt qualifizierte Seitenanker.|Größter Streamingzusatz; ein begrenzter Requery nach Ankerübernahme ist realer Preis. Kein Vollkatalogzwang und keine Abrufzeit als Beleg. Ohne neue Migration ist dieser Nutzen noch nicht verfügbar.|Tag1/Tag2/Tag4 mit realem SQL/React bewahrt Beginn1 und Verbrauch4 ohne Vollfallback.~Tag16 bleibt nach Restdiff/Remount ohne Neuitem und Neuzähler.~Später echter Zugang darf neues Fenster eröffnen; Wiederholung verlängert nichts.~Owner, Dienste, Epoch und veraltete Antworten werden verworfen.~Bestehende Anker und MotN-Zeiten bleiben wirksam; vier Seitenreads und null Vollfallbacks im Integrationslauf.
E07-001|Film und Serie mit gleicher TMDB-Nummer blenden sich nicht gegenseitig als gesehen aus.|Lokaler Seenabgleich prüft die beidseitige Werkart vor dem IDtreffer.|Sehr kleiner richtiger Fachguard; kein generelles Matchingrefactoring und keine neue Datenquelle.|Format8/9 und beide Film/Serie-Richtungen verhindern false seen.~Popularpool und bei gültiger Verfügbarkeit persönliche Karte bleiben enthalten.~Gleicher Typ/Identität bleibt gesehen; unbewertet allein reicht nicht.~Widersprechende IDs und typgebundener Titel/Jahr-Fallback behalten Schutz.~Master und markierte Katalogkandidaten werden im echten Feedpfad getestet, null Netz.
E07-002|ÖFI-Titel können mit belegter Identität sicher in aktuelle Kinokarten einfließen.|Bestehender Resolver ergänzt optionale annotations in Formaten8/9; Matcher bleibt streng.|Zusätzliche begrenzte Resolverarbeit und SQL-/Browservertrag. Optionales Scheitern erhält Grundfeed. Alter strenger Browser verwirft mit Annotation den gesamten Feed: kompatibler Rollout bleibt offen.|Echter Producer/Resolver mit lokalen Antworten und echter SQL-Persistenz liefert genau eine ÖFI-Karte samt Quellenmetadaten.~Beide Formate8/9 passieren neue Server/SQL/Browser. Eigene Gegenprobe zeigt zugleich alten Leserbruch.~Fehlbeleg, Remake, Typkonflikt, Mehrdeutigkeit und veraltete/fehlende Vorstellung erzeugen keine Karte.~Füller erhalten keine erfundene Popularität; Dienstfilter und 50er-Pool bestehen.
E08-001|Ein gespeicherter Geschwisterfund bleibt bei teilweisem Speicherfehler nutzbar und sichtbar.|Unveränderter Providerreceipt wird von expliziten Speicherzählern und erlaubter Präsentationsabstufung getrennt.|Zusätzlicher Antwortvertrag mit strikter Korrelation; notwendige Komplexität statt pauschaler Lockerung. Kein automatisches Wiederholen bezahlter Arbeit.|Echter Adapter/Handler/Service akzeptiert einen erfolgreichen und einen fehlgeschlagenen Upsert als confirmed/writes1/partial.~Speicherwarnung bleibt; initialer Controller fällt nicht pauschal auf unavailable.~Structured, providerpartial und elf Manipulationsfälle werden gegengeprüft.~Receipt bleibt unverändert; jeder Fall hat genau einen Mockproviderrequest.~Fund wird aus regulärem Pilotfeed nachgelesen; Kandidaten werden nicht direkt als persistiert dargestellt.
E08-002|Gleichzeitige Plattformstarts überschreiben einander nicht mehr.|Gemeinsamer Textfundschlüssel enthält Plattform; SQL migriert V1 zu V2 und nimmt alte Schreibschlüssel definiert entgegen.|Echte Identitätsmigration, die alte Event-UUIDs erhält. Sie erhält jedoch nicht den V1-Lesevertrag alter Browser. Frühere bereits überschriebene Plattformbelege werden nicht rekonstruiert.|Parser/Evaluator/Runner und realer SQL-Upsert erhalten beide Plattformen/Quellen.~Umgekehrte Reihenfolge ergibt gleichen fachlichen Endstand.~Replay bleibt no_change ohne neue Version.~Neue Leser erhalten migrierte Bestands-UUIDs/Versionen; alte Leser brauchen gesonderte Übergangslösung.~Account/Abobindung, Pause und strukturierter Pfad bleiben; keine zusätzlichen Providerrequests.
E08-003|Eigene Personenabos lassen sich auch bei leerem Suchkatalog entfernen.|Remove validiert gegen bestätigtes eigenes Abo statt gegen Anlagekatalog.|Entkoppelt gezielt eine Lebenszyklusaktion. Neue Anlage bleibt kataloggebunden; Fehlerzustände werden sichtbar.|Echter Dialog/Controller/Outbox entfernt aktives bestätigtes eigenes Abo genau einmal.~Bestätigter Feed/Reload hält Entfernung.~Pausiertes eigenes Abo wird ebenfalls entfernt.~Fremde/unbekannte/unbestätigte Identität und Kontextwechsel lösen keine Mutation aus.~Ablehnung, Sync- und Storagefehler zeigen Erklärung statt falscher Erfolgsmeldung.
E08-004|Gültige Freitextabos mit IDähnlichem Inhalt machen den gesamten Feed nicht mehr unlesbar.|Texttargets benutzen ihren eigenen Textvertrag; Nichttexttitel behalten Präfixsperre.|Schmale typabhängige Validation statt globale Lockerung. Echte Freitextlänge bleibt begrenzt.|Sieben Präfixe gehen durch Queue/SQL/Feed/frische Reconciliation.~Geschwisterabos und Funde bleiben lesbar.~Reguläres Pause/Remove funktioniert ohne DBreparatur.~Leertext, Nichtstrings, Überlänge und technische Nichttexttitel bleiben abgewiesen.~Normaltext, Feedvarianten und Accountgrenzen bleiben kontrolliert.
E08-005|Der Smokevertrag akzeptiert zulässige drei oder vier Freitext-Websuchen.|Zählerprüfung und Meldung entsprechen dem bestehenden maximalen Textvertrag1–4.|Reine Prüfwerkzeugkorrektur; Requests, Budget und Provenienz werden nicht erweitert.|Ein Providerrequest mit1,2,3,4 Suchen wird akzeptiert.~15 ungültige Zähler-/Providerkombinationen bleiben rot.~Phase, Präsentation, Receipt und Feed/Resultat bleiben validiert.~Echte lokale Adapter/Runner/Readbackkette führt drei Suchen durch; Smokezeichenfolge stimmt.
E09-001|Weitere Angaben ergänzen bestätigte Profilfilme, statt still den Bestand zu ersetzen.|Gemeinsame Rahmenübernahme vereinigt nach Master-ID oder eindeutiger Filmidentität; Richtungsänderung wird sichtbar.|Mehr Fachlogik für Duplikate, aber nur ein Annahmeknoten. Viele Ergänzungen können bestehende Größenlimits erreichen; fehlende Identität führt konservativ nicht zum Überschreiben.|A plus bestätigtes B speichert und lädt A+B.~Keine Auswahl, leere Teilliste und Abbruch erhalten Bestand.~Erneute Auswahl vermeidet Dublette; eindeutige Richtungskorrektur ist sichtbar.~Nicht mehr angebotener Altfilm bleibt erhalten.~Gemockte KI-Teilliste nutzt dieselbe endgültige Übernahme; nur bestätigter Vorschlag wird ergänzt.~Einwilligung, Vorschau, Validierung und Versionsschritt bleiben in Produkt-/Extraktionstests wirksam.
E09-002|Heute-/Morgen-Kinosuche verwechselt den6. nicht mit16. oder26.|Beide Suchzweige vergleichen vollständige Tages-/Monatstoken über denselben Helper.|Kleiner Parser für bereits normierte Anzeigezeiten; kein universeller Datumparser. Explizite Titelby-pässe und weiche Zeitsemantik bleiben bewusst erhalten.|6.9 schließt16/26 aus, auch nach echter Normalisierung/Fallback/Cache.~7.9 schließt17/27 aus.~Ausgegebene zugeordnete Zeiten enthalten nur erlaubte Tage.~Direkttitel, Zeit ohne Kino, Normalisierungsfenster sowie DST/Jahreswechsel haben Gegenproben.
E09-003|Kino-Restfilme außerhalb des angefragten Tages verschwinden vor Ranking und Limit.|Restzweig benutzt denselben Tagesfilter wie Masterzweig.|Kleine gemeinsame Logik; Kinofilme mit mindestens einem passenden Termin bleiben. Die Karte kann weiter zusätzliche Termine zeigen; das Ticket fordert hier die Filmauswahl.|Heute/morgen/übermorgen im echten normierten Programm wird korrekt getrennt.~Antwort, Finder-DOM und kompakte Globalliste zeigen nur passende Restfilme.~Mehrterminfilm bleibt bei mindestens einem passenden Termin.~Ohne Tag bleibt Bestand; Genre/Jahr/Titelverträge sind kontrolliert.~Gemischter Master-/Restbestand und beide Tage laufen mit null Netz.
E09-004|Vier vermeintlich grüne Asyncprüfungen laufen jetzt tatsächlich.|IIFEs werden aufgerufen; checkAsync lehnt unaufgerufene Funktionen ab.|Reiner Testfix ohne Produktänderung. Sentinelproben sind sinnvoll, weil sie das ursprüngliche falsche Grün ausschließen.|Alle vier Körper werden vom Originaltest betreten.~Ursprüngliche Assertions bestehen; normaler Test meldet149 erfolgreich.~Jeder einzelne Sentinel führt im eigenen Prozess zu Fehlerexit.~Funktionsobjekt wird ausdrücklich abgewiesen.
E10-001|Null und andere nicht objektförmige JSONrequests enden kontrolliert vor allen Außenwirkungen.|Schmale Objektwurzelprüfung direkt nach JSON.parse.|Bewusste Erweiterung des Formguards auf Arrays/Primitive; gültige Nullfelder bleiben zulässig. Kein Handlerumbau.|Null und Whitespace-null ergeben400 in beiden Aktivierungsmodi.~Mockaufrufzahl bleibt0 vor Auth/DB/Provider.~Originalfälle OPTIONS, NichtPOST und kaputtes JSON bestehen in separatem Handlerfilter.~Arrays und Primitive werden abgelehnt, null als Objektfeld bleibt gültig.
E10-002|Ein nach Headern gescheiterter Modellkatalog wird nicht mehr als erfolgreicher leerer Katalog verbucht.|Erfolg setzt fertig gelesene gültige Struktur voraus; Timeout und Antwortfehler schließen gezielt ab.|Zusätzliche Strukturvalidierung im vorhandenen Diagnosezweig. Gültige leere Liste bleibt als Diagnose erlaubt, P8 verlangt weiterhin eine ID.|Postheaderabort liefert Zeitgrenze, Fehler und genau einen Nullkostenabschluss.~Bodyfehler, invalidJSON/null/array/missing/bad-item werden nicht grün.~Originaler nichtleerer Katalog und gültiger leerer Katalog schließen einmal erfolgreich.~Originale Startablehnung, Vorheadernetzfehler und HTTPfehler bleiben wirksam.~P8-Originalblock stoppt ohne ID; Notaus/Registry-/Nullkostengrenzen sind mitgeprüft.
E10-003|Öffentliche Quellenadapter können nicht mehr nach erfolgreichen Headern unbegrenzt am Body hängen.|Timer deckt die gesamte begrenzte Bodydekodierung ab; Reader wird in finally freigegeben.|Kleine Lebensdauerreparatur am Transport. Reale Fetch-Abbruchwirkung bleibt Voraussetzung, nicht jeder beliebige Mock muss AbortSignal ignorieren dürfen.|Offener Body beider Adapter endet mit adapter-timeout innerhalb25ms plus Toleranz.~Stocken nach erstem Chunk endet ebenso.~Headerstall und rechtzeitiger gültiger Body bleiben korrekt.~Reader ist nach Fehler entsperrt und rechtzeitig fertiger Request wird nachträglich nicht abgebrochen.~32 Transportfälle erhalten HTTP/Rate/Type/Size/UTF8/JSONklassifikation.
E10-004|Gleiche TMDB-Nummern verschiedener Werkarten teilen keinen Filmwissenbericht oder laufenden Request.|Typed Kennungen an Filmwissengrenze, Typprüfung im Cache/Forecast und film-only Quellenfence; persönliche TMDB-Felder bleiben numerisch.|Hoher Migrations-/Rolloutpreis gegenüber einem bloßen Serienfence. Neuer Client passt nicht zum alten Server; alter Client nicht zum strikten neuen TMDBnormierer. Gemischter Betrieb braucht Übergang.|Film/Serie mit77 erzeugen getrennte Identität und In-flight-Keys.~Falscher Filmbericht wird auch nach IMDbmiss nicht als Serienbeleg akzeptiert.~tv-TMDB endet vor Quellen, Vorbereitung und Kosten.~Echter Forecast verwirft falschen Typ und meldet persönliche Schätzung statt Filmwissenprovenienz.~IMDb und movie-TMDB samt Quellensynthese und36 Formularfällen bleiben gültig.~PG17 migriert Filmkennungen, sperrt unsichere Nichtfilmaltzuordnung und trennt movie/tv/collection; Rolloutfrage bleibt separat offen.
E11-001|Sichtbare Standardanzahl12 begrenzt den Reminder tatsächlich auf12 Termine.|Auswahlwechsel setzt12 im Entwurf statt nur im Anzeigefallback.|Sehr kleiner UIzustandsfix; bewusstes Wechseln der Endart setzt den vorgesehenen Standard. Bestehende Anzahl bleibt beim bloßen Bearbeiten erhalten.|Fünf Reminderarten speichern unveränderten sichtbaren Standard12.~Termin12 fällig,13 nicht; ICS COUNT12.~Bestehende7 und explizite9 werden erhalten.~Wechsel von nie/datum nach Anzahl ist im Bearbeitungsmodus konsistent.~JSON-/LocalStorage-Rücklesen hält Werte; nie und Datum bleiben gültig.
E11-002|Persönlich empfohlene Kinokarten sind über Suche und Pinboard genauso erreichbar wie neutrale Karten.|Empfehlungslane erhält denselben stabilen Fokusanker, Wrapper und Öffnungssignal; ohne Ziel keine Quittierung.|Kleine Wiederherstellung eines gemeinsamen UIvertrags. Kein neues Ranking, kein RAF-Retryloop; Datenänderung kann ausstehenden Fokus erneut zustellen.|Mit/ohne Profil erhalten identische Programm-ID echten Fokus, Scroll und offene Details.~Mountauftrag und neuer Auftrag im geöffneten Tab sind geprüft.~Löschen des zugestellten Fokus schließt Details nicht.~Echte Appcallbackkette für Suche/Kinopin/Titelpin führt zum selben einmaligen Ziel.~Neutrale Karte und gematchte Masterkarte bleiben funktional.
E11-003|Legacy-Alles verknüpft widersprüchliche Werke nicht mehr allein über eine passende IDnummer.|Legacystatus und progressive Aktionen nutzen die vorhandene strenge Identitätsentscheidung.|Bewusster Verlust unsicherer alter Links; Gesehenhistorie bleibt. Bereits existierender WeakMapindex vermeidet zusätzliche lineare Indexbauten pro Karte.|TMDBtyp-/Jahrkonflikt liefert weder Statuszuordnung noch Navigation.~Weitere IDkonflikte und mehrdeutige Reihenfolgen verknüpfen nicht automatisch.~Falsch gespeicherte existierende ID wird bei Konflikt entfernt, Gesehenfelder erhalten.~Legacybrowser zeigt Erstellen statt falschem Link.~Gültige eindeutige Zuordnung sowie Missing-RPC-Fallback und progressive Kontrollen bestehen.
E11-004|Persönliche Kinoreminder öffnen bei aktuellem Mediathekmatch die richtige Filmkarte.|Klicktransport erhält die aktuell aufgelöste film_ref zusätzlich zur Programmreferenz.|Ein Referenzfeld im vorhandenen Pfad statt neuer Suchlogik. Gelöste/fehlende Ziele bleiben ohne irreführende Aktion.|Automatischer Reminder öffnet/fokussiert/scrollt echte Masterkarte.~Manuelle Verknüpfung und inzwischen angelegter Film verwenden aktuelle Referenz.~Neutrales Programmziel, Pin und Vorschlag bleiben Programm-/Filmidentitätstreu.~Detached/fehlende Ziele haben keinen falschen Öffnungsbutton.~Originalprojektion, Wochenplanklick, Appcallback und echte Kinozielkarte werden zusammen ausgeführt.
E11-005|Leere Remindertitel verursachen weder stillen Verlust noch unhandledRejection.|Trimvalidierung erklärt den Fehler im Formular; nullable Konstruktorergebnis wird vor Zugriff abgefangen.|Kleine lokale Eingabegrenze. Kein Datenmodellwechsel und keine bestehende Planlöschung.|Leerstring/Whitespace in Neu/Bearbeiten bei leerem/vorhandenem Plan zeigen Fehler.~Keine Writes, Planänderung oder unhandledRejection.~Korrektur im offenen Formular speichert genau einmal.~Gültige Pfade bleiben; Konstruktor-Null wird im produktiven Callback abgefangen.
E12-001|Radarvorschau und Schließenfläche bleiben an den Tabletgrenzen im Viewport.|Generisches Layerpadding wird für die vorhandene Vollhöhenregel bis760px konsistent.|Zwei CSSzeilen, keine neue Layoutarchitektur. Physische iPhone-Safe-Area bleibt unbelegt.|521,600,667quer und760: reale Dialog-/44px-Geometrie liegt im Viewport.~Autofokus und scrollTop0 benötigen keinen Rettungsscroll.~393/520 mobil und761/1280 desktop bleiben korrekt.~Touchclose, Abbrechen, Escape und Managerausnahme bestehen.~Chromium und WebKit prüfen alle Grenzbreiten; daraus folgt keine Geräteabnahme.
E12-002|Kino- und Streamingdetails sind direkt mit Tastatur erreichbar.|Benannte native Buttons mit aria-expanded ergänzen die bestehenden Disclosurewege.|Bewusster zusätzlicher Tabstopp; innere Aktionen bleiben eigene Ziele statt verschachtelter Buttons. Kleine UIänderung.|Kino neutral/Empfehlung: Tab, Enter/Space, Terminpin und Anlage erreichbar.~Streaming Alles/Neu mit ungesehen/gesehen/zugeordnet wird nativ bedient.~Innere Aktionen schalten Disclosure nicht nebenbei; Fokusnavigation öffnet gezielt.~Beide Browser prüfen Tastatur, aria-expanded, sichtbaren Zustand und Zuordnungsbedingungen.
E12-003|Schmale Wochenplaneditoren haben tatsächlich getrennte bedienbare Tagesflächen.|Grid bricht ab44px Mindestbreite um statt sieben Spalten zu erzwingen.|Ein CSSwechsel kann mehr vertikale Höhe brauchen; das ist der notwendige Preis echter Touchflächen. Daten-/Checkboxlogik bleibt gleich.|Vier Breiten mal vier Themes mal zwei Engines bestehen in Neu und Bearbeiten.~Jedes Label ist mindestens44x44 und vollständig enthalten.~Center/Edge-Taps aller sieben Labels ändern nur ihren Tag; Mindest-ein-Tag-Guard bleibt.~Gemessene Rechtecke und elementFromPoint statt bloßer Scrollbreite liegen als Geometrie-JSON vor.~Beide Editorwege verwenden unveränderte Komponenten und lokale Persistenz.
E13-001|Ein gerade entstandener Backlog wird vom Workflow als Rückstand statt falscher Vertragsfehler gemeldet.|Eine Zustandsäquivalenz entspricht jetzt der Corepriorität Backlog vor Idle.|Einzeiliger Parserfix; kein Scheduler-/Claim-/Providerumbau. Gültiger Rückstand bleibt Warnung, nicht erledigt.|Originalcore mit idleclaim und später fälligem Job liefert backlog/0/lag0.~Unveränderter extrahierter Workflowshell erreicht echte Warning und Step-Summary.~Die übrigen gültigen Kombinationen folgen weiterhin der gelesenen Zähler-/Zustandsformel.~16 inkonsistente Zustände/Zähler/Extras/Limits bleiben im Originalshell rot.~Nur claimDue und inspectBacklog werden aufgerufen; Anbieter/Mail/Settlement sind harte Fehlerstubs.
E13-002|Abgelaufene Mailratefenster können begrenzt verschwinden, ohne alte Versandoperationen erneut freizugeben.|Bestehende Retention erhält indizierte Bucketzählung und limitierte Löschung.|Additive SQLfunktionkopie ist lang, fachliches Delta klein. Operationsledger wächst bewusst weiter; dessen Änderung wäre ein eigenes Idempotenzkonzept.|Dryrun meldet nur abgelaufene Buckets ohne Mutation; Monitorfixture erkennt Bedarf.~Disabledpurge löscht nichts; Limits1/200/500 und Wiederholung gelten.~Aktive Counter bleiben; zwölf parallele Begins halten Limit4 trotz Purge.~Wiederholte Fenster werden begrenzt entfernt; gesperrte Zeilen werden übersprungen.~Accepted/rejected/unknown/claimed-IDs bleiben Replay/Conflict; Begin/Finishdefinitionen bytegleich.
E13-003|Functionhash und Dirtyprüfung übersehen keine lokal transitiv importierten Module mehr.|Ein deterministischer Importabschluss ersetzt die unvollständige Dateiliste für beide Zwecke.|Parserabhängigkeit im Prüfwerkzeug, strikt nichtliteral-dynamische Imports werden abgewiesen. Keine Änderung des Deploynachweises zu einem Remotenachweis.|Alle elf aktuellen lokalen Module gehören zur Closure.~Jede uncommittete Closureänderung und neu hinzugefügte Abhängigkeit wird erfasst.~Commitänderung je Modul ändert beide Hashes; Wiederholung ist deterministisch.~Parserproben decken Reexports, Typimports, Literaldynamicimports, Zyklen und Täuschtext ab.~Rohe Gitblobs, Config/JWT/Projekt/Functionbindung und separater Readback bleiben erhalten.
E13-004|Der Browsergate prüft wieder den tatsächlich gewollten Hilfehero und erreicht Folgeassertionen.|Nur erwarteter Text plus ausdrückliches Verbot des alten Texts ändern sich.|Reiner Testfix; kein Produkttextwechsel, keine abgeschwächte Fixture.|Ausgewählter Originaltest besteht frisch in Chromium und WebKit.~Settingshilfe zeigt persönlichen Plattformhero.~Nachfolgende Menü/Audit/Touchassertionen laufen, retries0 und Netzfence bleiben.~Production-Copytest prüft neuen und fehlenden alten Text separat.
E14-001|Radar-Faktenlookup erhält das bereits vorhandene verifizierbare Werkjahr.|Effektiver SQLkontext projiziert das vorhandene releaseYear; Readergrenze bleibt streng.|Migration ersetzt eine eng identifizierte Stelle der bestehenden Funktion und bricht bei unerwarteter Definition ab. Kein Rückschluss/Erraten fehlender Jahre.|Werkanlage plus separates Abo über echte RPCs liefern Jahr im effektiven Kontext.~Echter Kontext führt über Produktreader zu Fakten im Suchadapterrequest.~Sechs Varianten prüfen fehlend/ungültig/widersprüchlich ohne Suche zu blockieren.~Keine zusätzlichen Suchen oder Cachewrites; vorhandene Rollen-/Targetpfade bleiben.~Film und Serie laufen an derselben SQL-/Readergrenze, Serie mit E05-002normalisierung.
E14-002|Katalog neu laden aktualisiert auch einen noch frischen progressiven Seitenrecord.|Eigene monotone Refreshrevision fließt in vorhandenen Controllerkontext.|Sehr kleines Signal statt neuem Cachemanager. Expliziter Refresh verursacht berechtigt einen zusätzlichen Seitenread, normale Wiederverwendung bleibt.|Inaktiver frischer Record wird trotz wertgleicher Dienste/Master/Marker neu angefordert.~Neue Metadatenversion wird im Seitenzustand sichtbar; Legacyreads allein zählen nicht.~Mehrere Render erzeugen nur einen Wiederanlauf je manueller Revision.~Vorherige späte Antwort wird durch Generation/Epoch verworfen.~Ohne manuellen Refresh bleibt frischer Record; Neuanker und14Tage bleiben unverändert.
'''
assessments={}
for raw in DATA.strip().splitlines():
    short,benefit,change,risk,proofs=raw.split('|')
    assessments['KD-REV-'+short]={'benefit':benefit,'behaviorChange':change,'riskAndComplexity':risk,'proofs':proofs.split('~')}
assert len(assessments)==49
prior=json.loads((ROOT/'docs/review/2026-09-fixes/evidence/verification/FINAL_REVIEW.json').read_text())
criteria=json.loads((OUT/'acceptance-original.json').read_text())
issues=[]
for index in prior['issues']:
    tid=index['id']; a=assessments[tid]
    assert len(criteria[tid])==len(a['proofs']), (tid,len(criteria[tid]),len(a['proofs']))
    locations=[]
    for s in index['sourceLocations']:
        lines=(ROOT/s['file']).read_text().splitlines()
        if lines[s['line']-1].strip():
            locations.append({'file':s['file'],'line':s['line'],'excerpt':lines[s['line']-1].strip()})
    tests=[]
    for t in index['reviewedTestSources']:
        f=t['file']; name=pathlib.Path(f).stem+'.log'
        if f=='authdriver_test.mjs':name='authdriver.log'
        if f=='ai_task_test.ts':name='ai_task_P06.log'
        if f=='tests/private-v1/private-v1.spec.mjs':name='private_v1_hero.log'
        if (OUT/name).exists() and not any(z['source']==f for z in tests):
            tests.append({'source':f,'log':name,'result':'PASS','sha256':hashlib.sha256((OUT/name).read_bytes()).hexdigest()})
    if tid in ['KD-REV-E10-001','KD-REV-E10-002']:
        tests.append({'source':'ai_task_test.ts','log':'ai_task_neighbor_guards.log','result':'PASS','sha256':hashlib.sha256((OUT/'ai_task_neighbor_guards.log').read_bytes()).hexdigest()})
    if tid=='KD-REV-E07-002': tests.append({'source':'repro-oefi-compat.mjs','log':'repro-oefi-compat.json','result':'CONFIRMED_ROLLOUT_INCOMPATIBILITY'})
    assert tests,tid
    ticket=ROOT/index['ticketFile']
    cause=re.search(r'## Ursache[^\n]*\n(.*?)(?=\n## |\Z)',ticket.read_text(),re.S)
    issue={'id':tid,'title':index['title'].split(' · ',1)[-1],'package':index['package'],
      'status':'ERLEDIGT','statusScope':'Ursprüngliche lokale Fehlerursache und Abnahme am vollständigen Kandidaten; keine Mischbetrieb-/Deploymentfreigabe.',
      'decision':'BEHALTEN','decisionReason':'Die Änderung beseitigt die ursprüngliche Ursache am betroffenen Vertragsknoten; der belegte Nutzeneffekt rechtfertigt die hier ausgewiesenen Kosten.',
      'benefit':a['benefit'],'behaviorChange':a['behaviorChange'],'riskAndComplexity':a['riskAndComplexity'],
      'originalTicket':index['ticketFile'],'originalTicketSha256':hashlib.sha256(ticket.read_bytes()).hexdigest(),
      'originalCause':re.sub(r'\[([^\]]+)\]\([^)]+\)',r'\1',cause.group(1).strip().split('\n\n')[0]).replace('\n',' ') if cause else 'Ursache und Auslöser stehen im verlinkten Originalticket.',
      'baselineCauseSource':index['ticketFile']+'#ursache-und-fundstellen','baselineComparison':'Originalauslöser und Abnahme gelesen; betroffene Baseline-/Kandidatenänderung und ihre Nachbarn abgeglichen. Baselinebeleg stammt aus Ticket und frischem git diff, nicht aus erneuter Komplettausführung des Baselinesystems.',
      'sourceLocations':locations,'tests':tests,
      'criteria':[{'number':n,'criterion':re.sub(r'\[([^\]]+)\]\([^)]+\)',r'\1',c).replace('\n',' '),'status':'ERLEDIGT','evidence':p,'testLogs':[t['log'] for t in tests]} for n,(c,p) in enumerate(zip(criteria[tid],a['proofs']),1)],
      'rolloutStatus':'NICHT FREIGEGEBEN','rolloutRequirement':'Separater Lieferauftrag und gezielte Readbacks; in dieser Prüfung keine Remoteänderung.'}
    if tid=='KD-REV-E07-002':
        issue['rolloutStatus']='OFFEN';issue['rolloutRequirement']='R-OFI: alter Browser verwirft Feed mit annotations vollständig. Neuer SQL-/Producerstand darf dem alten Leser nicht ungefiltert serviert werden.'
    if tid=='KD-REV-E08-002':
        issue['rolloutStatus']='OFFEN';issue['rolloutRequirement']='R-RADAR: migrierte release:v2-Bestandsfunde sind für alte release:v1-only Reader nicht lesbar. V1-Schreibkompatibilität allein erfüllt keinen Altclientvertrag.'
    if tid=='KD-REV-E10-004':
        issue['rolloutStatus']='OFFEN';issue['rolloutRequirement']='R-TMDB: typed neue Requests und alte Numericrequests benötigen einen expliziten Client-/Function-/SQL-Übergang; keine sichere Release-Reihenfolge durch bloß gleichzeitiges Deployen.'
    issues.append(issue)
assert len(issues)==len({x['id'] for x in issues})==49
assert sum(len(x['criteria']) for x in issues)==239

interactions=[
 {'tickets':['E02-001','E02-002','E03-001','E03-002'],'node':'authDriver Credentialcommit; accountDriver Remoteübernahme; uebernahme Transition',
  'cause':'Asynchrone Arbeit wurde gegen überholte Identität/Revision oder unvollständigen Bestand übernommen.',
  'assessment':'Die Ursache ist verwandt, aber die Schreibknoten und Bedeutungen sind verschieden: Logininstanz, Remote-Revision und vollständige Adoption dürfen nicht ein generischer boolean-current-Guard werden.',
  'smallerOption':'E02-001/E02-002 sind bereits in derselben Refresh-/Commitlogik vereint. Eine globale Async-Transaktionsabstraktion würde Auth, Gastrestore und Datentopfsync neu koppeln, ohne nachgewiesene Sonderfälle zu entfernen.',
  'recommendation':'BEHALTEN; kein zusätzlicher gemeinsamer Zustandsmanager. Cross-tab/401/Pull/Adoption-Proben getrennt erhalten.'},
 {'tickets':['E04-001','E05-003','E06-002','E07-001','E08-002','E10-004','E11-003','E14-001'],'node':'Projektion und Bestätigung von Werkidentität an verschiedenen Datenverträgen',
  'cause':'Typ, Jahr, Plattform oder echte aktuelle Bestandszugehörigkeit ging bei Projektion/Schlüsselbildung verloren.',
  'assessment':'Gleiche allgemeine Fehlerklasse bedeutet keine identische fachliche Identität: Releaseplattform, persönliche Master-ID, TMDB-Namespace und ÖFI-Quellbeleg sind unterschiedliche Verträge.',
  'smallerOption':'E06-002/E11-003 teilen bereits ordneStreamingPageTitelZu und gecachten erstelleMediathekIdentitaetsIndex. Dadurch entfallen widersprüchliche Status-/Navigationsentscheidungen; Revert würde die belegten Konflikte wieder öffnen.',
  'recommendation':'BEHALTEN; kein Universal-IDresolver. Gemeinsamen bestehenden Mappingknoten weiter durch Delete/Recreate, Remakes, Typ-/Jahr-/IDkonflikte prüfen.'},
 {'tickets':['E05-002','E14-001'],'node':'kd_radar_websearch_context → readCachedTitleFactsContext → kd_title_facts_lookup',
  'cause':'An der gemeinsam genutzten Faktensuche fehlte je eine notwendige Information: korrektes Werkartvokabular und gespeichertes Bezugsjahr.',
  'assessment':'Ein reiner Readerpatch kann ein im SQLkontext nicht geliefertes Jahr nicht wiederherstellen; ein reiner SQLpatch korrigiert keine serie/series-Serialisierung.',
  'smallerOption':'Die zwei schmalen Änderungen sind bereits das kleinere gemeinsame Ergebnis. Einen neuen Enricher vor den Reader zu setzen würde zusätzliche Kopplung und potenzielle Requests erzeugen.',
  'recommendation':'BEHALTEN; gemeinsame produktnahe SQL→Reader→Adapter-Prüfung ist vorhanden und frisch grün.'},
 {'tickets':['E09-002','E09-003'],'node':'gesuchteKinoTage und passendeKinoZeiten in src/lib/finder.js',
  'cause':'Master- und Restzweig hatten divergierende beziehungsweise fehlende harte Tagesfilter.',
  'assessment':'Eine kleine gemeinsame Korrektur ersetzt tatsächlich zwei lokale Datumsentscheidungen und ist bereits integriert.',
  'smallerOption':'Keine weitere Kalenderabstraktion: bestehender normalisierter Anzeigevertrag genügt. Universalparser brächte Zeitzonen-/Formatkopplung ohne ticketbezogenen Nutzen.',
  'recommendation':'BEHALTEN; Heute/Morgen, Fulltoken, DST/Jahreswechsel und direkter Titelby-pass sind getrennte Kontrollfälle.'},
 {'tickets':['E04-002','E09-001','E04-005'],'node':'Bewertungsinhalt, Profilrahmenannahme und kandidatenweises Stapelergebnis',
  'cause':'Einstiegs-/Teilerfolgsflags ersetzten teilweise die Prüfung des endgültig gespeicherten Inhalts.',
  'assessment':'E04-002 teilt bereits den reinen Bewertungsvergleich; E09-001 vereinigt am einen finalen Rahmenknoten; E04-005 speichert pro Kandidat. Das sind die tatsächlichen Bestätigungsgrenzen.',
  'smallerOption':'Generischer Merge-and-save-Helfer würde Profilidentität, Bewertungssemantik und Batchfehlerstatus vermischen; keine nachgewiesene Zeilen- oder Sonderfallersparnis.',
  'recommendation':'BEHALTEN; keine zusätzliche Persistenzabstraktion.'},
 {'tickets':['E01-001','E04-003','E11-002','E11-004','E12-002'],'node':'Start-Projektion → Appnavigation → lokale Fokus-/Disclosurezustände',
  'cause':'Eine Anzeige-/Navigationsvariante verlor vorhandene Identität oder quittierte vor sichtbarem Ziel.',
  'assessment':'Ein Pin kann ausstehend sein, ein Fokus braucht sichtbares DOM, ein Reminder aktuelle Quelle. Diese Unterschiede sind produktrelevant.',
  'smallerOption':'Ein gemeinsamer Navigationscontroller würde mehrere Tabzustände neu koppeln. Aktuell reichen unveränderte Appcallbacks plus lokale sichtbare Zielguards und native Buttons.',
  'recommendation':'BEHALTEN; dieselben Nutzerwege komponentenübergreifend testen, keinen Routerumbau beginnen.'},
 {'tickets':['E06-001','E06-003','E14-002','E05-001'],'node':'Streamingpage-Kontext/Fristen plus eigenständiges Known/Discover-Paar',
  'cause':'Quellgeneration, fachlicher Ablauf, persönlicher Verbrauch und manuelle Refreshabsicht sind unabhängige Informationen, die vorher nicht vollständig weitergetragen wurden.',
  'assessment':'Ein einzelner Cache-TTL oder globales Leeren kann diese vier Verträge nicht korrekt ersetzen.',
  'smallerOption':'sourceExpiresAt, newAnchors und Refreshrevision sind zielgenaue Felder am bestehenden Controller. Zusammenlegung der SQLmigration ist bereits erfolgt; alte Migrationen zu editieren wäre kein sicherer Vereinfachungsschritt.',
  'recommendation':'BEHALTEN; keinen pauschalen Vollkatalogrefresh einführen. Anker-Requery ist begrenzt belegt.'},
 {'tickets':['E10-002','E10-003'],'node':'Bodylesedauer und Abschluss des Modell-/Quellentransports',
  'cause':'HTTPheader wurden zu früh als Ende des relevanten Vorgangs behandelt.',
  'assessment':'Gemeinsames Prinzip, aber verschiedene Aufräum-/Kostenverträge: öffentlicher Quellenreader versus protokollierte Diagnosereservierung.',
  'smallerOption':'Ein neuer Fetchwrapper müsste Ressourcen-, Fehler- und Kostenklassen angleichen und würde bestehende Sicherheitsgrenzen koppeln.',
  'recommendation':'BEHALTEN; Timerlebensdauer und vollständige Erfolgsstruktur an ihren bestehenden Knoten halten.'},
 {'tickets':['E02-003','E03-003','E08-005','E09-004','E13-001','E13-003','E13-004'],'node':'Verschiedene Prüfwerkzeuge lesen oder erzeugen den Produktvertrag',
  'cause':'Test-/Workflowvertrag driftete vom Produkt, war unvollständig oder lief gar nicht.',
  'assessment':'Nicht sieben Produktdefekte. Die Änderungen erhöhen Beweiskraft und Zuverlässigkeit der Werkzeuge; sie rechtfertigen keine gemeinsame neue Testplattform.',
  'smallerOption':'Gezielte Originalcodeausführung, Sentinels, Closuregraph und gültige Fixture sind jeweils bereits die kleineren Korrekturen.',
  'recommendation':'BEHALTEN; Assertions weder pauschal lockern noch alte Solltexte zurücknehmen.'},
]
rollout=[
 {'id':'R-OFI','tickets':['KD-REV-E07-002'],'status':'OFFEN','decision':'KORRIGIEREN',
  'evidence':'Eigene repro-oefi-compat.mjs führt echten Kandidatenproducer/Resolver mit lokalen Antworten aus und lädt den Baseline-Browservertrag. Format8 und9: jeweils50 Items, eine Annotation, neuer Leser true, alter false/feed-shape-invalid. Nach Entfernen nur von annotations akzeptiert alter Leser denselben Feed.',
  'files':['supabase/functions/entdecken-daily-task/runner.js','supabase/functions/entdecken-daily-task/contract.js','src/lib/webDiscoveryFeed.js','supabase/migrations/20260917130000_review_entdecken_ofi_identity.sql'],
  'retainedContract':'Neue Leser brauchen die sichere ÖFIidentität; alte Leser müssen weiterhin ihren bisherigen gültigen50er-Feed erhalten.',
  'recommendedOption':'Explizite kompatible Leseprojektion beziehungsweise versionierter Readvertrag, der alten Lesern annotations nicht liefert; neue Writer/SQL erst innerhalb dieses Übergangs aktivieren. Reines frontend-first reicht für offene/offline Altclients ohne zusätzlichen Gültigkeitsvertrag nicht als vollständiger Nachweis.',
  'testsRequired':'Matrix alt/neu Writer, Persistenz und Reader für8/9; alter Feed ohne Annotation bleibt lesbar; neuer Reader erhält sichere ÖFIkarte; Programme ohne Beleg bleiben ausgeschlossen.',
  'couplingCost':'Version/Capability muss am wirklichen Feedread bekannt sein; sonst getrennte Ablage/Version nötig. Noch kein getesteter Patch und keine Freigabe.'},
 {'id':'R-RADAR','tickets':['KD-REV-E08-002'],'status':'OFFEN','decision':'KORRIGIEREN',
  'evidence':'Kandidatvalidator akzeptiert release:v[12], Baseline nurv1. Migration ersetzt V1schlüssel aller Textfunde durch V2, behält Finding-/Eventversion-IDs und akzeptiert alte Writer. Master meldet26 reale V1-Funde; diese Bestandszahl wurde hier nicht remote gelesen.',
  'files':['supabase/functions/radar-websearch-task/contract.js','supabase/migrations/20260917100000_review_radar_text_identity.sql','src/lib/radarPilotContracts.js'],
  'retainedContract':'Zwei Plattformstarts müssen erhalten bleiben; alte stabile Eventidentitäten und Altclient-Lesbarkeit dürfen nicht durch bloße Writerkompatibilität ersetzt werden.',
  'recommendedOption':'Interne V2-Plattformidentität und explizit kompatible Altclient-Feedprojektion prüfen; alternativ nachgewiesener Clientversionszaun mit entsprechend sichtbarer Altclientbehandlung. Nicht die neue Identität zurückdrehen, da sonst Plattformverlust zurückkommt.',
  'testsRequired':'V1bestand migrieren, alte/neue Feedreader, zwei Plattformen, Pause/Remove/Reviews und idempotenter Replay über Versionsgrenzen.',
  'couplingCost':'Feedprojektion und Schlüsselidentität müssen konsistent versioniert werden. Keine blanket Zusage, dass ein simples Umbenennen des V2präfixes den Hash-/IDvertrag erfüllt.'},
 {'id':'R-TMDB','tickets':['KD-REV-E10-004'],'status':'OFFEN','decision':'KORRIGIEREN',
  'evidence':'Neue Helper senden movie:/tv:-Werte, alter Normierer akzeptiert nur Numeric. Neuer SQLnormierer akzeptiert nur Typed; Baselineclient sendet Numeric. Master meldetkeine vorhandenen TMDB-Filmwissenkennungen, was Datenmigration vereinfacht, aber den Requestbruch nicht löst.',
  'files':['src/lib/filmwissen.js','src/services/filmwissen.js','supabase/functions/ai-task/index.ts','supabase/migrations/20260917110000_review_filmwissen_identity.sql'],
  'retainedContract':'Keine Film/Serien-Verwechslung; gültiger IMDb-/Film-TMDBnutzen und unabhängige persönliche Prognose bleiben nutzbar.',
  'recommendedOption':'Explicitly typed neuer Vertrag plus serverseitige kontrollierte Legacybehandlung, die Numeric nicht blind als Serie oder Film rät. Altrequests ohne sichere Werkart kontrolliert ausgrenzen oder gesicherte Filmzuordnung prüfen. Gemeinsames zeitgleiches Deploy ist bei offenen/offline Clients kein Vertrag.',
  'smallerAlternative':'Originalticket erlaubt einen guard-first Umfang: Serien-TMDB vor Cache/Adapter stoppen, Cachetyp prüfen und Numeric-Filmvertrag vorerst erhalten. Das könnte Typmigration/Trigger/mehrere Spezialfälle ersparen, verzichtet aber auf getrennte Typed-Cacheadressen und verlangt besonders sichere Alt-Mappingbehandlung. Es ist eine Scopeentscheidung, kein bereits belegter besserer Patch.',
  'testsRequired':'Alt/neu Client gegen alt/neu Function+SQL; Film/Serie gleiche Nummer; IMDbmiss plus TMDBfallback; falscher Cachetyp; persönliche Prognose ohne Filmwissen; keine versehentliche Umdeutung von Numeric.',
  'couplingCost':'Ein Übergangsadapter kostet weniger als unkontrollierte globale Client/Server-Kopplung, muss aber nach Ende des Altvertrags bewusst entfernt werden.'},
]

def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT,text=True)
assert git('rev-parse','HEAD').strip()==CANDIDATE
dirty=git('status','--porcelain')
assert not dirty,dirty
changed=git('diff','--name-only',BASE,CANDIDATE).splitlines()
sourcefiles=[f for f in changed if f.startswith(('src/','supabase/','.github/','tools/'))]
manifest=[]
for f in sourcefiles:
    data=(ROOT/f).read_bytes()
    manifest.append({'file':f,'sha256':hashlib.sha256(data).hexdigest(),'lines':len(data.splitlines()),'comparison':'Affected implementation and neighboring contract reviewed; baseline delta archived.'})
(OUT/'source-manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False))
(OUT/'baseline-to-candidate.patch').write_text(git('diff','--no-ext-diff',BASE,CANDIDATE,'--','src','supabase','.github','tools','local_data_safety_test.mjs','blogprofilanalyse_test.mjs','tests/private-v1/private-v1.spec.mjs'))
testLogs=[]
for f in sorted(OUT.glob('*.log')):
    if '.sandbox-failed.' in f.name:continue
    testLogs.append({'file':f.name,'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'tail':f.read_text().splitlines()[-4:]})
geometry=re.search(r'Geometry evidence: (.+/results.json)',(OUT/'review49_p09_browser_test.log').read_text())
if geometry and pathlib.Path(geometry[1]).exists():shutil.copyfile(geometry[1],OUT/'p09-browser-geometry.json')
result={'schema':'kinodreieck-independent-benefit-audit-v1','candidateCommit':CANDIDATE,'baselineCommit':BASE,'worktree':str(ROOT),
 'auditor':'Separate independent Astra/xhigh reviewer; no builder role, no further delegates.',
 'completedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),
 'counts':{'tickets':49,'criteria':239,'ERLEDIGT':49,'OFFEN':0,'NICHT BELEGT':0,'rolloutContractsOpen':3},
 'overallDecision':'Lokale Fixes BEHALTEN. Gemischte Auslieferung KORRIGIEREN/gesperrt; keine Releasefreigabe.',
 'meaning':'ERLEDIGT bezeichnet allein den abgegrenzten lokalen Originalfehler am vollständigen Kandidaten. Für gemischten Altclient-/Backendbetrieb bestehen separate bestätigte offene Verträge. Ein globales Versprechen nur Vorteile wäre falsch.',
 'methodology':['Alle49 Originaltickets samt Ursachen/Auslösern/239 Abnahmen gelesen. Originalcriteria nochmals direkt aus den Ticketdateien extrahiert.',
 'Eigener sauberer Detachedworktree am exakten Kandidaten; frischer Baseline-Diff, betroffener Code und benachbarte Lese-/Schreibverträge geprüft.',
 'Voriger unabhängiger Bericht nur als Quellen-/Testindex verwendet; dessen Ergebnis und Kriterienevidenz nicht übernommen.',
 'Gezielte Originaltests erneut ausgeführt; echte Komponenten, unverändert extrahierte Appcallbacks, originale Workflowshell, Handler und SQLfunktionen. Mocks/Synthesedaten liegen an Außen-/Konto-/Providergrenzen.',
 'Eigene adversariale Altclientprobe für ÖFI ergänzt. Kein vollständiger neuer Repositoryreview; keine vollständige Testsuite, kein Build-/Deploy-/Remote-/Providerlauf.',
 'Vier initiale PGstarts scheiterten am Sandbox-shmget vor fachlicher Prüfung; identische Tests nach automatischer Freigabe lokal erneut ausgeführt und grün. Ursprüngliche Fehlerlogs bleiben erhalten. Keine Assertions gelockert.',
 'Browser- und PGgestelle erzeugen lokale temporäre Laufdateien; eigene Skripte, Logs und Berichte liegen ausschließlich im eigenen Evidenzverzeichnis. Produktworktree blieb sauber.'],
 'issues':issues,'commonCausesAndSmallerOptions':interactions,'rolloutFindings':rollout,
 'limits':['Keine Aussage über CI, Deploymentbytegleichheit, aktiven Functionstand, aktuellen Anbieterzustand oder physisches iPhone/PWA.',
 'Sechs Migrationen laut aktuellem Masterbefund unremote; Staging und Produktion teilen dasselbe Supabaseprojekt. Ein Staging-SQLwrite wäre daher gemeinsame Außenwirkung.',
 '26 Radar-V1funde und null TMDB-Filmwissenbestandskennungen wurden vom Master übermittelt, hier nicht remote verifiziert.',
 'E13-F005 bleibt separat ungeklärt und ist kein50. Ticket.',
 'Die frühere Baseline wurde nicht als Gesamtsystem erneut ausgeführt; ihr Fehlernachweis liegt in den gelesenen Originaltickets und dem unabhängigen statischen Vorher/Nachher-Abgleich.',
 'Ein neuer umfangreicher Umbau wurde nicht empirisch validiert. Die Alternativen sind Entscheidungen mit expliziten Folgeprüfungen, keine fertig gebauten Ersatzfixes.'],
 'testEvidence':testLogs,'sourceManifest':'source-manifest.json','baselineDiff':'baseline-to-candidate.patch','workingTreeClean':True}
(OUT/'REVIEW.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')

md=['# Unabhängige Nutzen- und Regressionsnachprüfung der 49 Fixes','',
 f'Kandidat `{CANDIDATE}` gegen `{BASE}`. Eigener sauberer Detachedworktree: `{ROOT}`. Keine Produktänderung, kein Remote-/Providerlauf.',
 '', '**Entscheidung: Die 49 lokalen Reparaturen beibehalten. Alle 239 ursprünglichen lokalen Abnahmekriterien sind belegt. Der gemeinsame Rollout bleibt wegen drei Altclientverträgen offen.** Ein Versprechen „nur Vorteile“ wäre falsch: zusätzliche Mutexabhängigkeit, konservativ fehlende Zuordnungen, begrenzte Zusatzreads und versionierte Backendverträge sind echte Kosten.',
 '', '## Beweisgrenze','']
md.extend('- '+x for x in result['methodology'])
md+=['','Die folgenden Statuswerte gelten für den ursprünglichen lokalen Fehler. „Behalten“ ist keine Genehmigung, den Kandidaten gegen das alte gemeinsame Backend auszuliefern. Die Rolloutentscheidung steht gesondert darunter.','',
 '## Genau 49 Ergebniszeilen','','| Ticket | Lokaler Status | Urteil | Belegter Nutzen |','|---|---|---|---|']
for i in issues:md.append(f"| {i['id']} | {i['status']} | {i['decision']} | {i['benefit']} |")
md+=['','## Bestätigte offene Auslieferungsverträge','',
 'Staging und Produktion teilen laut Master das Supabaseprojekt `bscjgwcntapobyxsiyce`; sechs neue Migrationen sind noch nicht remote. Der vorhandene Radar-V1bestand und die fehlenden TMDB-Filmwissenaltkennungen ändern die folgenden Request-/Readerverträge nicht. Diese Zustandsangaben wurden hier nicht remote gelesen.','']
for r in rollout:
 md += [f"### {r['id']} — {', '.join(r['tickets'])}",'',f"**{r['status']} / {r['decision']}.** {r['evidence']}",'',
  f"Erhaltener Vertrag: {r['retainedContract']}",f"Empfehlung: {r['recommendedOption']}"]
 if r.get('smallerAlternative'):md+=['',r['smallerAlternative']]
 md+=['',f"Nötiger Nachweis: {r['testsRequired']}",f"Neue Kopplung/Kosten: {r['couplingCost']}",'',
  'Betroffene Dateien: '+', '.join(f'[{f}]({ROOT/f})' for f in r['files'])+'.','']
md+=['Eigener reproduzierbarer Zusatzbeleg: [Script](repro-oefi-compat.mjs), [Ergebnis](repro-oefi-compat.json). Der alte Validator wurde aus dem Basiscommit gelesen; nur der notwendige Importpfad wurde auf die bytegleiche lokale Datendatei umgebunden. Alle externen Fetches sind gesperrt beziehungsweise durch injizierte lokale Antworten ersetzt.','',
 '## Gemeinsame Ursachen und kleinere Alternativen','']
for n in interactions:
 md += [f"### {', '.join(n['tickets'])}",'',f"Gemeinsamer Knoten: {n['node']}.",n['cause'],n['assessment'],'',n['smallerOption'],n['recommendation'],'']
md+=['## Einzelabgleich aller Abnahmen','']
for i in issues:
 md += [f"### {i['id']} · {i['title']}",'',f"**{i['status']} · {i['decision']}.** {i['benefit']}",
  f"Ursprüngliche Ursache: {i['originalCause']}",
  f"Verhalten: {i['behaviorChange']}",f"Risiko und Komplexität: {i['riskAndComplexity']}",
  f"Urteil: {i['decisionReason']}",'',f"Originalquelle: [{i['id']}]({ROOT/i['originalTicket']}). Vorher/Nachher: [frischer Kandidatendiff](baseline-to-candidate.patch).",
  'Aktuelle Fundstellen: '+', '.join(f"[{s['file']}:{s['line']}]({ROOT/s['file']}:{s['line']})" for s in i['sourceLocations'])+'.',
  'Frische Belege: '+', '.join(f"[{t['log']}]({t['log']})" for t in i['tests'])+'.','']
 for c in i['criteria']:
  md += [f"{c['number']}. **{c['status']}** — {c['criterion']}",f"   Nachweis: {c['evidence']}"]
 if i['rolloutStatus']=='OFFEN':md+=['',f"**Rollout separat OFFEN:** {i['rolloutRequirement']}"]
 md+=['']
md+=['## Nachvollziehbarkeit und verbleibende Grenzen','',
 '[Maschinenbericht mit49 eindeutigen Tickets und239 Kriterien](REVIEW.json), [direkt extrahierte Originalabnahme](acceptance-original.json), [Quellhashes](source-manifest.json), [Originalticket-Hashes](ticket-sources.json), [Browsergeometrie](p09-browser-geometry.json).','']
md.extend('- '+x for x in result['limits'])
md+=['','Alle neu ausgeführten Einzelprüfungen und ihre Logs sind im JSON unter `testEvidence` verzeichnet. Deno wurde ohne Netzrecht und mit `--cached-only` ausgeführt. Die sechs neuen Handlerfälle sowie gezielte alte Nachbarguards bestehen; das übrige Handlerfile wurde bewusst nicht als vollständige Suite gestartet.','']
(OUT/'REVIEW.md').write_text('\n'.join(md))
print(json.dumps({'issues':len(issues),'criteria':sum(len(x['criteria']) for x in issues),'files':len(sourcefiles),'logs':len(testLogs),'md':str(OUT/'REVIEW.md'),'json':str(OUT/'REVIEW.json')},ensure_ascii=False))
